# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_rss',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
